services:
  - type: web
    name: fh-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: INTERNAL_API_KEY
        generateValue: true
      - key: PORT
        value: 10000
